//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPPROJECT3
{
    using System;
    using System.Collections.Generic;
    
    public partial class clase
    {
        public int id { get; set; }
        public string dia { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<int> asignatura { get; set; }
        public string aula { get; set; }
        public Nullable<int> profesor { get; set; }
        public string seccion { get; set; }
    
        public virtual materias materias { get; set; }
        public virtual profesoress profesoress { get; set; }
    }
}
