//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPPROJECT3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_aabd33_ctpmqstestEntities : DbContext
    {
        public db_aabd33_ctpmqstestEntities()
            : base("name=db_aabd33_ctpmqstestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<clase> clase { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<especialidades> especialidades { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<profesoress> profesoress { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
    }
}
