//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPPROJECT3
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estudiantes()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public Nullable<int> especialidad { get; set; }
        public string CelularE { get; set; }
        public string CorreoE { get; set; }
        public string Nombre_Encargado { get; set; }
        public string Apellido_Encargado { get; set; }
        public string Apellido2_Encargado { get; set; }
        public string Numero_Encargado { get; set; }
        public string Correo_Encargado { get; set; }
        public string tipoEstudiante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
    }
}
