//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPPROJECT3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        public int IdSeccion { get; set; }
        public string cedula { get; set; }
        public int ProfesorGuia { get; set; }
        public string año { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual profesoress profesoress { get; set; }
        public virtual Secciones Secciones { get; set; }
    }
}
