//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiantes
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public Nullable<int> especialidad { get; set; }
        public string CelularE { get; set; }
        public string CorreoE { get; set; }
        public string Nombre_Encargado { get; set; }
        public string Apellido_Encargado { get; set; }
        public string Apellido2_Encargado { get; set; }
        public string Numero_Encargado { get; set; }
        public string Correo_Encargado { get; set; }
        public string tipoEstudiante { get; set; }
    }
}
